### ISSUE TITLE
Failed to run tests due to Cannot read property 'slice' of null

### ISSUE THREAD

**Issue by deguich** [MystK/vscode-mocha-two#1]
* Operating system: Windows 10
* VSCode version: 1.12.2
* Node 7.4.0
* Mocha 3.4.2

**Describe the situation:**
F1 => Mocha: Run all tests

Error shown : Failed to run tests due to Cannot read property 'slice' of null

It seems Mocha-latte fixed this problem ?
https://github.com/compulim/vscode-mocha/issues/5

**Comment by MystK** [comment]
Howdy! Is this a file that you saved already? Could you paste the snippet?

Antoine
________________________________
